name: Create a new Release Tag
on:
  workflow_dispatch: 
  create:
    branches: 
      - release/**
  push:
    branches: 
      - release/**
    tags:
      - 'v*'
jobs:
   new-release:
      runs-on: ubuntu-latest 
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog 
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'chore(release): {version}'
          tag-prefix: 'v'
          skip-version-file: 'true'
      
      - name: Create Release
        id: createrelease
        uses: actions/create-release@v1 
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}