name: Create GitHub Release
on:
  workflow_dispatch: 
  push:
    tags:
      - '*'
jobs:
   new-release:
      runs-on: ubuntu-latest 
      permissions:
        contents: write
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create-release
        uses: actions/create-release@v1 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          