name: SDK CI/CD
on:
  workflow_dispatch: # runs manually
  create:
    branches:
      - release/*
  push:
    branches:
      - release/*
jobs:
  stage_build:
    name: 'Build SDK Stage'
    env: 
      BUILD_CONFIG: 'Release'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        dotnet-version:
          - '7.0.x'
          - '6.0.x'
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
    timeout-minutes: 5
    steps:
    - name: Setup .NET SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Checkout source
      uses: actions/checkout@v3

    - name: Change directory (src)
      run: cd src

    - name: Restore (dotnet restore)
      run: dotnet restore --verbosity normal        
    
    - name: Build (dotnet build)
      run: dotnet build --configuration $BUILD_CONFIG --no-restore

    - name: Test (dotnet test)
      run: dotnet test --configuration $BUILD_CONFIG --no-restore --no-build --verbosity normal

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: sdk-artifacts
        path: |
          /home/runner/work/SDK/SDK/src/CloudLab.SDK/bin/Release/
          /home/runner/work/SDK/SDK/src/CloudLab.SDK.MongoDB/bin/Release/
