name: SDK CI/CD
on:
  workflow_dispatch: # runs manually
  create:
    branches:
      - release/*
  push:
    branches:
      - release/*
jobs:
  stage_build:
    name: 'Build SDK Stage'
    env: 
      BUILD_CONFIG: 'Release'
      SOLUTION_NAME: 'src/CloudLab.SDK.sln'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dotnet-version:
          - '7.0.x'
          - '6.0.x'
    timeout-minutes: 5
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup .NET SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore (dotnet restore)
      run: dotnet restore $SOLUTION --verbosity normal        
    
    - name: Build (dotnet build)
      run: dotnet build $SOLUTION_NAME --configuration $BUILD_CONFIG --no-restore

    - name: Test (dotnet test)
      run: dotnet test $SOLUTION_NAME --configuration $BUILD_CONFIG --no-restore --no-build --verbosity normal
