name: SDK Packages CI/CD (net6.0/net7.0)
on:
  workflow_dispatch: # runs manually
  create:
    branches:
      - release/* # On creating a new branch called release/*
  push:
    branches:
      - release/* # On push to branch called release/*
  release:
    types: 
      - published # On publish a new release on GitHub
jobs:
  build-linux:
    name: Linux Build Stage
    env: 
      BUILD_CONFIG: 'Release'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dotnet-version:
          - '7.0.x' # Already produces net6.0 and net7.0 binaries due the <TargetFrameworks> MSBuild property
        project-paths:
          - ./src/CloudLab.SDK/CloudLab.SDK.csproj
          - ./src/CloudLab.SDK.MongoDB/CloudLab.SDK.MongoDB.csproj
          - ./src/CloudLab.SDK.Tests/CloudLab.SDK.Tests.csproj
          - ./src/CloudLab.SDK.Tests/CloudLab.SDK.Tests.csproj
    timeout-minutes: 5
    steps:
    # SETUP STAGE - dotnet versions install
    - name: Setup .NET SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}      

    - name: Checkout source
      uses: actions/checkout@v3

    # RESTORE STAGE - dotnet restore **/*.csproj
    - name: RESTORE STAGE - dotnet restore **/*.csproj
      run: dotnet restore ${{ matrix.project-paths }} --verbosity detailed

    # BUILD STAGE - dotnet build **/*.csproj
    - name: BUILD STAGE - dotnet build **/*.csproj
      run: dotnet build ${{ matrix.project-paths }} --configuration $BUILD_CONFIG --no-restore --verbosity detailed

    # TEST STAGE - dotnet test **/*.csproj
    - name: TEST STAGE - dotnet test **/*.csproj
      run: dotnet test ${{ matrix.project-paths }} --configuration $BUILD_CONFIG --no-restore --no-build --verbosity detailed

    # PUBLISH ARTIFACTS STAGE - **/bin/Release/
    - name: PUBLISH ARTIFACTS STAGE - CloudLab.SDK binaries
      uses: actions/checkout@v3
      with:
        name: sdk-artifacts
        path: ./src/CloudLab.SDK/bin/Release/
        if-no-files-found: error
        retention-days: 7

    - name: PUBLISH ARTIFACTS STAGE - CloudLab.SDK.MongoDB binaries
      uses: actions/checkout@v3
      with:
        name: sdk-mongodb-artifacts
        path: ./src/CloudLab.SDK.MongoDB/bin/Release/
        if-no-files-found: error
        retention-days: 7

  #publish-github-packages:
  #  name: Publish to GitHub Package Repository Stage
  #  runs-on: ubuntu-latest
  #  needs: build-linux
  #  steps:
  #  - name: Push to GitHub Package Repository
  #    run: dotnet nuget push **\*.nupkg --api-key ${{secrets.GITHUB_TOKEN}} --source "https://nuget.pkg.github.com/cloudlabtech/index.json" --skip-duplicate
  
  #publish-nugetorg:
  #  name: Publish to NuGet.org Package Repository Stage
  #  runs-on: ubuntu-latest
  #  needs: build-linux
  #  steps:
  #  - name: Push to NuGet.org
  #    run: dotnet nuget push **\*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate    