name: Release to NuGet.org
on:
  workflow_dispatch:
  create:
    branches: 
      - release/**
  push:
    branches: 
      - release/**
  pull_request:
    branches: 
      - release/**
  release:
    types: 
      - published
jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'src/CloudLab.SDK.sln'  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x', '6.0.x' ]    
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore $SOLUTION --verbosity normal

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

    - name: Test
      run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --no-restore --no-build --verbosity normal

    - name: Push to NuGet
      run: dotnet nuget push **\*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate